### ISSUE TITLE
kerchunk / notebook issues in quarto

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#102]
Hi @amfriesz and @betolink , thought it would be easier to share this all here as we figure it out - 

I've merged Aaron's 3 kerchunk notebooks (PODAAC, LPDAAC, GES DISC) into the main branch, and tried rendering after [adding them to _quarto.yml](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/_quarto.yml#L54-L58) and preview the site. There were issues, so first off I: 

- removed any `---` line breaks that can confuse yaml parsers
- added a first raw cell that is a yaml "title"
- commented out the `hv.plot` final cells because that's given us trouble in the past 

With those changes, it was still hanging with the GES DISC MERRA2 notebook. That is still currently not included in the _quarto.yml ([it's commented out](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/_quarto.yml#L54-L58))

Even with only the PODAAC and LPDAAC examples, it's still taking a loooong time to `quarto preview` - that's true in 2i2c where I was building it, and also with the GitHub Action. @betolink would the be something you can look into, and I/we can also ask J.J. about it? Thanks!

**Comment by betolink** [comment]
I think this may be because these notebooks use Holoviews/Bokeh. `HVPlot` injects a lot of Javascript and CSS into the notebook ([in the order of megabytes](https://raw.githubusercontent.com/NASA-Openscapes/earthdata-cloud-cookbook/main/examples/GESDISC/GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb)) and perhaps Quarto is having issues parsing all of this. 

An easy workaround is that If we clean the notebook output(restart kernel and clean output) before pushing to the repo we should be fine with Quarto (with the downside that we won't see the results of the computations). Another potential solutions could involve converting the notebooks into HTML before pushing them to the repo and telling Quarto to not process those...

**Comment by jules32** [comment]
This is going so much faster following J.J.'s commit (see thread https://github.com/quarto-dev/quarto-cli/issues/857)! 🎉 

Closing this issue
