### ISSUE TITLE
Create citation for cookbook

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/earthdata-cloud-cookbook#178]
New issue branched from https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/153

- [x] create GitHub release
- [x] get DOI from Zenodo
- [x] add DOI badge to README ([example](https://github.com/Openscapes/series/blob/main/README.md)); [commit](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/commit/4a825bf8b7fe1dd476019704f107449cc3e76177)
- [x] add citation text: pull request https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/191

**Comment by stefaniebutland** [comment]
[Citing the Turing Way](https://the-turing-way.netlify.app/welcome.html#citing-the-turing-way) text is great

**Comment by stefaniebutland** [comment]
DOI from Zenodo: https://zenodo.org/record/7786711

@jules32 do you want any edits to Cite As? Was automatically populated:
![Screenshot 2023-03-30 at 11 29 43 AM](https://user-images.githubusercontent.com/11927811/228930822-8be1b830-49e8-416c-87eb-c2bb46b7c80c.png)

**Comment by jules32** [comment]
Hi Stef, yes, please update the author list so that it is NASA Mentors: 

Andy Barrett • Chris Battisto • Brandon Bottomley • Aaron Friesz • Alexis Hunzinger • Mahsa Jami • Alex Lewandowski • Bri Lind • Luis Lopez • Catalina Oaida Taglialatela • Celia Ou • Jack McNelis • Cassie Nickles • Brianna Pagán • Sargent Shriver • Amy Steiker • Michele Thornton • Makhan Virdi • Jess Welch

**Comment by stefaniebutland** [comment]
author list updated in Zenodo. 

![Screenshot 2023-04-04 at 5 58 26 PM](https://user-images.githubusercontent.com/11927811/229954577-bacef74a-7ace-4ed4-a882-3068c5368af7.png)

added to Cookbook in Add citation text #191

**Comment by stefaniebutland** [comment]
done: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/#citation
