### ISSUE TITLE
Add new "How do I... access data locally with wget and curl" guide

### ISSUE THREAD

**Issue by asteiker** [NASA-Openscapes/earthdata-cloud-cookbook#329]
As NSIDC DAAC begins publishing more data in Earthdata Cloud and removing access to our on-prem data copies, we identified the need to provide guidance on how to programmatically download data from the command line using the new HTTPS URLs from CloudFront. We would like to add a new How-to guide under the "Access data locally" section to include this additional guidance for non-python users.

**Comment by jules32** [comment]
Part of the conversation in coworking: Maybe have a section and link to https://urs.earthdata.nasa.gov/documentation/for_users/data_access/curl_and_wget rather than recreating here

And then have opinionated approaches using earthaccess? Maybe with a terminal wrapper if people are looking to use terminal (but don't need to get into wget/curl?)

**Comment by jules32** [comment]
Mahsa's screenshare and starting notes in today's Coworking doc: https://docs.google.com/document/d/1KDFO4hre7HU40IXQ4ffg9djQcWMYnu1Ho64M9nkUpbI/edit

**Comment by mjami00** [comment]
I updated the markdown document Julie created. https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/wget-curl/how-tos/access-data/access-data-command-line.md 
@asteiker feel free to update this draft as needed.
